project:
  type: website

website:
  title: "Diana-C-Rodriguez.github.io-blog"
  navbar:
    right:
      - href: blog.qmd
        text: blog
      - href: index2.qmd
        text: about
      - icon: github
        href: https://github.com/Diana-C-Rodriguez.github.io
      - icon: twitter
        href: https://twitter.com/@dcr200002
     
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

