---
title: "Welcome To My Blog"
author: "Diana Rodriguez"
date: "2022-09-16"
categories: [personal blog]
---

Thank you for visiting my blog. In this section you can find additional information related to my personal and professional experiences.

I was born in El Paso, Texas to immigrant parents. My mother is from Mexico, and my father was born in Colombia. Being Latina born of immigrant parents, is one of the most significant parts of my identity.

In 2022, I married an incredible woman, Jacky. My wife, and who I believe I am capable of being because of her, is the other most significant part of my identity.

For ten years, I worked in a variety of justice system positions ranging from a youth crisis intervention liaison, to repeat violent offender unit juvenile probation officer. During these years, I also completed my bachelors and masters degree. Ultimately, I left my position as a juvenile probation officer to return to school and complete my doctorate degree. I am a second year PhD student at The University of Texas at Dallas, and focus a majority of my studies on restorative justice practices, and juvenile delinquency.

For the last three years I have been developing a restorative just principle based program. Over these years, I have been working to develop a sound program manual based on literature and theory. My hope is to complete my PhD, and launch programming focus on providing alternative to punitive sanction programming to at-risk youth.

-Diana Rodriguez
